### ISSUE TITLE
Allow accessing `Data` within cost functions

### ISSUE THREAD

**Issue by Kixiron** [egraphs-good/egg#103]
Currently cost functions can neither access the egraph nor access each eclass's analysis data, but this is really important for getting good cost analysis

**Comment by mwillsey** [comment]
I believe this commit adds the necessary documentation: https://github.com/egraphs-good/egg/commit/5f1828496bb491a9ab954387d36f531016d3865a

**Comment by Kixiron** [comment]
Thanks!
