### ISSUE TITLE
Analysis::make doesn't have `self`

### ISSUE THREAD

**Issue by bjchambers** [egraphs-good/egg#109]
This makes it impossible for the analysis to provide information (such as a global symbol table) to lookup analysis information. Is there a reason that only the `merge` method can access the analysis itself?

**Comment by mwillsey** [comment]
Make has access to the egraph, which contains the analysis.

**Comment by bjchambers** [comment]
Ah. That will work. It seems a bit weird to get the instance of self indirectly, but this will work. Thanks for the quick response!

**Comment by bjchambers** [comment]
That will work. It seems a bit odd to get the instance of self indirectly. Thanks for the quick response!

**Comment by mwillsey** [comment]
Yes it’s a little weird, but make may want access to the egraph as well, and passing both would be awkward.
