### ISSUE TITLE
Any intentions for matching arbitrary-length parameters?

### ISSUE THREAD

**Issue by liangyiliang** [egraphs-good/egg#110]
Hi, I am currently working on a project that requires a pattern that matches any enodes / eclasses that has a certain operator, regardless of the number of parameters. In particular, I want to have a pattern that matches all of the following:
```
(ListValues 1)
(ListValues 1 2 3)
(ListValues 1 5 6 7 8)
(ListValues 1 2 ... 100)
...
```

Does Egg currently offer native support for matching these things? Thank you!

**Comment by mwillsey** [comment]
Right now, egg can support terms of variable length, but you cannot write patterns to match variable length. You'd have to write one pattern for every length you care about. I do not presently plan to support variadic patterns.

In this specific case, you could try using a cons-list instead
```
(Cons 1 Nil)
(Cons 1 (Cons 2 Nil))
(Cons 1 (Cons 2 rest))
```
