### ISSUE TITLE
Non-local cost function

### ISSUE THREAD

**Issue by rkjones4** [egraphs-good/egg#127]
Hi!

Thank you for releasing this great project and for providing such comprehensive documentation!

I was wondering if egg in its current form provides support for non-local cost functions. I would like to design a Extractor / cost-function pairing that does not penalize re-using the same variable. For example, given the expression

(+ a b), with a rewrite rule b -> (* a a), I would like the cost function to identify (+ a (* a a)) as the minimum cost expression (as only one variable is used). 

From what I understand, this type of cost function is not currently supported by the Extractor class, because computing the best expression for each e-class depends on which variables have already been used. Is this understanding correct? If not, please let me know how I should design the Extractor / cost function to support this use case. 

My idea for adding this functionality into the egg framework is that (for my use case) the costs hashmap in the Extractor class should be keyed by both the e-class id and the available variables, and should contain a value tuple of both the cost and available variables of the best expression. 

Please let me know if this seems like a sensible way to extend egg to support my use case, or if there is an alternative strategy I should instead consider.

Thank you and all the best,
Kenny

**Comment by mwillsey** [comment]
Also, I am working on an ILP based extraction procedure right now! 

https://github.com/egraphs-good/egg/pull/128

You may not be able to do the exact thing in you comment, since that would rely on using a variable costing nothing at all on reuse, as opposed to a small amount. But it will do common subexpression elimination in general.

**Comment by mwillsey** [comment]
On second thought, you can totally achieve this with that branch my making operators expensive and variables cheap. I'm closing this as solved for now. Feel free to open again if something comes up!
