### ISSUE TITLE
Modifying the e-graph while merging `Analysis` data.

### ISSUE THREAD

**Issue by rosekunkel** [egraphs-good/egg#134]
I would like to make an analysis which contains e-class `Id`s. Specifically, for each e-class, I want to store the `Id` of the e-class which represents the same expression, except the de Bruijn indices of all of the free variables have been shifted by one (if that e-class exists). So, for example, if the e-class contains the node `$0 + $1`, I want to store the  `Id` of the e-class containing `$1 + $2`. I want to represent this as an `Analysis<Data = Option<Id>>`. The issue comes when implementing `Analysis::merge`:
```rust
fn merge(&self, a: &mut Option<Id>, b: Option<Id>) -> DidMerge {
  let data = match (a, b) {
    (None, None) => None,
    (Some(a), None) => Some(a),
    (None, Some(b)) => Some(b),
    (Some(a), Some(b)) => // ???
  }
  // ...
}
```
Logically, what should happen in the `(Some(a), Some(b))` case is something like this:
```rust
egraph.union(a, b);
Some(a)
```
but `Analysis::merge` doesn't have access to the e-graph, so that's impossible. It seems like modifying the e-graph during the merger is somehow possible using `Analysis::modify`, but the documentation doesn't say when that function is called or what kind of things you can do with it.

**Comment by mwillsey** [comment]
Upon further reflection, giving `merge` mutable access to the e-graph is actually really tricky. When `merge` is called, the merged e-classes are actually temporarily removed from the e-graph! So someone looking at it might be very surprised.

This is indeed the purpose of the `modify` function, and it has access to anything. `modify` is called basically right after `merge`, but it allows the e-graph to put everything back, so the `merge` is complete by the time `modify` is called.

So I think the right thing here is to give `merge` a `&mut self` to the `Analysis`, allowing you to store data "globally" on the e-graph during a `merge`. Then you can use `modify` to consume that data. Something like:

```rust
// It's convenient to have your analysis impl Default
#[derive(Default)] 
struct MyAnalysis {
    to_union: Vec<(Id, Id)>,
}

impl Analysis for MyAnalysis {
    fn merge(&mut self, ...) -> ... {
        // put stuff in self.to_union
    }
    fn modify(egraph: &mut EGraph<...>, _: Id) {
        let to_union = std::mem::take(&mut egraph.analysis.to_union);
        for (a, b) in to_union {
            egraph.union(a, b)
        }
    }
}
```

cc @bjchambers

**Comment by mwillsey** [comment]
I think this is addressed now. Feel free to re-open if needed.
