### ISSUE TITLE
Plans for upcoming releases?

### ISSUE THREAD

**Issue by bjchambers** [egraphs-good/egg#138]
The last release (0.6.0) looks like it is over a year old. A lot of good changes have been made, and it would be helpful to get a release up on `crates.io` so that those of us using using versions from there can update. Any chance a release could be made sometime?

**Comment by mwillsey** [comment]
Yes, I would like to cut a release soon. I'm working on it :)

**Comment by mwillsey** [comment]
0.7.0 is out! https://crates.io/crates/egg
