### ISSUE TITLE
Problems upgrading

### ISSUE THREAD

**Issue by bjchambers** [egraphs-good/egg#140]
Ran into two problems upgrading. One was easy enough to work around but the other may be worth discussing.

1. `display_op` was removed and you now implement `Display` for the `Language` type. This feels a bit weird though since it only displays the operator, not the whole `Language` struct. This may be better as a separate trait like `FromOp`?
2. The `FromOp` requires `Error`, but there are a few cases where that won't be implemented. For instance -- previously my errors were `String`, but that doesn't implement `Error`. I'm also now using the `anyhow` crate for errors, and that also doesn't implement `Error` (https://docs.rs/anyhow/1.0.51/anyhow/struct.Error.html#impl-AsRef%3Cdyn%20Error%20+%20%27static%3E). Seems like that requirement may be needlessly restrictive. Could it instead require `Display + 'static` or `AsRef<dyn Error + 'static>` or something like that?

**Comment by mwillsey** [comment]
Thanks for pointing these out!

1. Yes, I agree that's a little awkward. The next version of egg will have a "first-class" notion of just the operator, so that will make things more clear. The Op will then implement fromstr and display.
2. I think `Error` is still "best practice", but I'm happy to be corrected. `String` [can be converted](https://doc.rust-lang.org/stable/std/convert/trait.From.html#impl-From%3CString%3E-1) into `Error`. And I think the [`thiserror`](https://github.com/dtolnay/thiserror) crate is the "right" way to quickly create new kinds of errors. This [issue](https://github.com/dtolnay/thiserror) mentions what you are saying, that it's a little painful to put an `anyhow::Error` into a `impl std::error::Error`, but it has a workaround too. I think you should probably use `thiserror` though.

Hopefully that's helpful!

**Comment by bjchambers** [comment]
re: 1 -- cool, I'll live with that for now.

I think `thiserror` is useful in some contexts -- `anyhow` and `thiserror` are by the same author. They suggest using `anyhow` in cases where you don't care which error is being returned. I tend to use `thiserror` in cases where I'm writing a library and `anyhow` more for applications. I guess the question is does the additional restriction to `Error` actually provide functionality, over even just requiring `'static`)?

https://github.com/dtolnay/anyhow#comparison-to-thiserror

I guess my point / though here is that while these alternatives exist, if the `Error` restriction doesn't add value to the `trait`, then it should be up to the user to choose to use an `Error` or not.

**Comment by bjchambers** [comment]
Also note that that conversion from `String` is to `dyn Error` -- which means you need to have it in a `Box` or behind a `&`. Since `FromOp` requires `Error` it can't be used. If it instead required something that allowed a `dyn Error` behind a reference (such as `AsRef<dyn Error + 'static>`), then `anyhow` already would with it.

**Comment by bjchambers** [comment]
Specifically, `String` can't be converted to an `Error + 'static`. It could be `Into<dyn Error> + 'static` for instance.

**Comment by bjchambers** [comment]
Eg., https://doc.rust-lang.org/std/str/trait.FromStr.html `FromStr` doesn't require that the `Error` implements `Error`.

**Comment by bjchambers** [comment]
Also, `Var` changed to return a `VarParseError` but that type isn't exposed. It is public in `subst`, but `subst` isn't public. So there is no way to include that in a `thiserror`.

**Comment by mwillsey** [comment]
I think #141 should address this?

**Comment by bjchambers** [comment]
Yeah, I think that'll do it for the error type requirement. Not sure about the `VarParseError` being not visible -- I'm just going to convert it to a `String` for now.

**Comment by mwillsey** [comment]
Yeah I'd rather not expose VarParseError for now. Do you need a new cargo release?

**Comment by bjchambers** [comment]
I should be good without (worked around the issues), but it may be useful for others.

The problem is that if I write code that attempts to use a variable, it gets a `VarParseError`. The only thing I can do with it is format it as a `String` (discarding the backtrace and such). Eg., if I write code that has it's own searcher or applier, it needs to parse a `Var`, and gets the error. But I can't put that into a `thiserror` enum because I can't mention the type. I guess it's OK as a `String` (this is what it previously was), but that seems to then defeat the point of creating an enum?

**Comment by bjchambers** [comment]
And thanks for the quick responses!

**Comment by mwillsey** [comment]
I think that's right. I just don't want to expose it publicly right now, at least not before I re-organize the code into modules with a prelude.
