### ISSUE TITLE
Running into bugs/errors with unexpected expression equivalences

### ISSUE THREAD

**Issue by rkjones4** [egraphs-good/egg#143]
Hi!

I've been observing some unexpected behavior when extracting "minimum cost expressions", such that the returned expression is not equivalent to the "input" expression under the rewrite rules I am applying.

**(Case 1).** 

If I have an expression like "(Move (Prim a b) 0.1 0.0)" and a rewrite rule like "(Move ?x 0.0 0.0)" => "?x" , then the best expression will unexpectedly be "(Prim a b)". Note that with the same rewrite rule, "(Move (Prim a b) 0.0 0.0)" becomes "(Prim a b)" and "(Move (Prim a b) 0.0 0.1)" becomes "(Move (Prim a b) 0.0 0.1)", which is the expected behavior.

This makes me think there is some issue in how the searcher in the rewrite rule is checking for matches in the middle arguments of a function -- is there some implicit assumption that each function should be taking in only 2 arguments?

**(Case 2).** 

Saturating the e-graph with many rewrites can return an expression with a completely different type. For instance, say I have an expression like:

"(Union (Move (Prim B_F_0 B_F_1) B_F_2 B_F_3) (Prim B_F_4 B_F_5))" 

where each B_F_X is some continuous variable.

If I apply rewrite rules that relate different B_F_X's under parametric relationships (e.g. "B_F_0" => "(+ B_F_5 2.0)") and support basic arithmetic rules (e.g. "(+ ?a 0.0)" => "?a"), then I will occasionally extract a "best expression" such as "-1", which clearly would not be equivalent to the input expression. Note this only happens when the e-graph is saturated, if I constrain the iter limit or the node limit of the runner, then this behavior is not observed -> this leads me to believe there might be some subtle bug I am running into related to e-class book-keeping, where non-equivalent e-classes are somehow being unioned together. 

**I'm attaching a minimum working example that recreates both of these errors.** 
[main.txt](https://github.com/egraphs-good/egg/files/7714047/main.txt)

Please let me know if I can provide any additional context / help. 
Thank you!

**Comment by mwillsey** [comment]
Hello! Thanks for submitting this!

Case 1 has exposed a bug in egg version 0.7. I'm patching it right now and will then move onto case 2.

**Comment by mwillsey** [comment]
Ok, I think the patch mentioned addresses both issues, which were symptoms of the same bug. I will re-release egg soon.

Let me know if there's anything else needed for this issue!

**Comment by rkjones4** [comment]
Yes the patch fixed these bugs, thank you so much!
