### ISSUE TITLE
Add not-equal conditions

### ISSUE THREAD

**Issue by mwillsey** [egraphs-good/egg#15]
Sometimes you only want to rewrite if something is not equal.

This gets a little dicey because things may become equal later, but we should support it as it's pretty common.

**Comment by chadbrewbaker** [comment]
Example?

**Comment by mwillsey** [comment]
@chadbrewbaker `x / x = 1` iff `x != 0` is a good example.

**Comment by mwillsey** [comment]
I'm closing this as I don't think it's worth supporting, since it's too easy to misuse.

**Comment by vitrun** [comment]
> `x / x = 1` iff `x != 0` is a good example.

Hey, @mwillsey How would you implement your example without the support of not-equal conditions?  We have even more complex situations when trying to simplify math expressions, for example,  `tan(θ) = sin(θ) / cos(θ)` requires `θ != 1/2*pi + k*pi`.

**Comment by Bastacyclop** [comment]
Maybe you can represent `θ != 1/2*pi + k*pi` as `(θ != 1/2*pi + k) == true` or `(θ == 1/2*pi + k) == false` in the e-graph instead of relying on e-graph equivalence classes?

**Comment by vitrun** [comment]
@Bastacyclop Thanks for your reply. Maybe it's not about the way to write conditions, it's about the way to check it. Think about `tan((3+4-3*2)/2*pi)`, before simplifying `(3+4-3*2)/2*pi` to `1/2*pi`,  I can not tell (θ != 1/2*pi + k) is true or false. In general, `t` in `tan(t)` can be an arbitrary complex term, making it hard to write the condition.

**Comment by yihozhang** [comment]
Right. In general when two terms are not in the same e-class, it is hard to tell if they are semantically inequivalent or just not yet merged. So the use of not-equal condition is tricky and will sometimes make the rule unsound. For example, `x / x => 1 if x != 0` could be unsound if egg later discovers that `x` is indeed equivalent to `0`.

One thing you could probably do is to have a mini theorem prover inside egg. For example, you can have (multi-pattern) rules for reasoning about whether a predicate is true. E.g., you can have a rule that merges the predicate `θ != 1/2*pi + k` with the e-class where constant `true` is in when you know `θ != 1/2*pi + k` holds. Later you can use this as the rewrite condition in your real rewrite rules. This is made easy with the multi-rewrite feature of egg. See [here](https://github.com/egraphs-good/egg/blob/main/tests/datalog.rs) for some examples on multi rewrites in egg.
