### ISSUE TITLE
Difficulty working with multiple expressions in an egraph

### ISSUE THREAD

**Issue by spencerking** [egraphs-good/egg#151]
I am new to egg and have been experimenting with defining my own language, example below

```
use egg::{*, rewrite as rw};

define_language! {
    pub enum TestLang {
	"+" = Add([Id; 2]),
	"-" = Subtract([Id; 2]),
        "defun" = Defun([Id; 2]),
	Symbol(Symbol),
    }
}

fn main() {
    let mut rules: Vec<Rewrite<TestLang, ()>> = vec![
	rw!("add-0"; "(+ ?a 0)" => "(?a)"),
    ];
    
    let start = "(+ 5 0)".parse().unwrap();

    let mut runner = Runner::default().with_expr(&start).run(&rules);

    runner.print_report();

    let mut extractor = Extractor::new(&runner.egraph, AstSize);
    let (best_cost, best_expr) = extractor.find_best(runner.roots[0]);
    println!("{}", start);
    println!("best cost: {}, best expr {}", best_cost, best_expr);
}
```

This works as expected for the simple case of `(+ 5 0)` and for more complex cases such as `(defun x (- 1 (+ 5 0)))` and so on. My issue is that I would like to experiment with optimizing programs containing multiple expressions, such as `(defun x 5) (+ x 0)`. All of the examples I've seen only operate on a single expression; is it possible to optimize over an entire program, or would each expression need to be optimized individually? I am aware that `Runner` has a `with_egraph` method, but I'm not sure if that helps in this case.

**Comment by spencerking** [comment]
Perhaps a better question would be: is there a straightforward way to generate a sexp from multiple expressions? Ultimately where I'm hoping to be able to go is to optimize something like `(expr a) (expr b) (expr c)` to `(expr d) (expr c)`.

**Comment by mwillsey** [comment]
You're right egg is designed to optimize one expression into another. You could define a way to turn multiple expressions into one, something like `(seq expr1 (seq expr2 expr3))` perhaps.

The difficulty with a full program as in your example is the notion of binding. `x` is defined to be `5` in some contexts, but not others. And the e-graph's notion of equivalence, so it would like to consider `x` equivalent to `5` either globally or not at all.

Using equality saturation for these kinds of programs typically entails transforming them first into dataflow, and then using that in the e-graph.

**Comment by spencerking** [comment]
This is fine to close. I have some ideas about how to generate sexps for my language, I just need to play with it a little more.
