### ISSUE TITLE
Runner stopping due to node limit not approached

### ISSUE THREAD

**Issue by eu49** [egraphs-good/egg#154]
Hi Max,

I use the Runner with usize::MAX as the e-graph size limit. However, the stopping reason of the runner turns out to be Some(NodeLimit(11476)), although I don't anticipate that e-graph size would reach MAX if the runner didn't stop (and there are no loops in the e-graph). Could there be a limit on the e-graph size specified somewhere else in the codebase which precedes what the user specifies through with_node_limit?

Thanks!

**Comment by mwillsey** [comment]
Hmm that sounds fishy. Could you show a code snippet where you set up the
runner?

**Comment by eu49** [comment]
I assigned MAX to time limit, iter limit, node limit, and used the SimpleScheduler so that the e-graph can be fully saturated. But somehow ```runner.stop_reason``` gives ```Some(NodeLimit(11476))```.

```
let runner = Runner::default().with_expr(&start).run(rules).with_time_limit(Duration::from_secs(u64::MAX)).with_iter_limit(usize::MAX).with_node_limit(usize::MAX).with_scheduler(SimpleScheduler);
```

**Comment by mwillsey** [comment]
I can't see a reason that would be the case. Can you point me to some code where I can reproduce the bug?

**Comment by eu49** [comment]
I just created a mirror and added this test to ```math.rs```. Sent you a github invitation. Thank you!

**Comment by mwillsey** [comment]
Ah! The issue is the order of method calls in the builder pattern. `run()` actually runs the `Runner` with the arguments you have so far. So your `with_*_limit` calls aren't doing anything.

I moved `.run()` to the end of the chain and things work as I would expect them too (it saturates after 12 iterations).
