### ISSUE TITLE
Mismatched parentheses

### ISSUE THREAD

**Issue by intrigus** [egraphs-good/egg#213]
Hi,
I've ported egg to Java and so had to rewrite parsing SExprs.

My parser rightfully (?) choked on these two lines that contain mismatched parentheses I believe:
```rust
egraph.add_expr(&"(f a (g a))))".parse().
egraph.add_expr(&"(f a (g b))))".parse().unwrap());
```
https://github.com/egraphs-good/egg/blob/f6e837a11a7fd9a56514e843c87ffff80179fbf6/src/pattern.rs

**Question: Am I missing something or is the SExpr parser off egg just ignoring this mismatch?**

**Comment by mwillsey** [comment]
You are correct. egg currently uses the [`symbolic_expressions`](https://docs.rs/symbolic_expressions/latest/symbolic_expressions/) library, which for some reason stops parsing as soon as it completes an s-expression. I'm not a fan of this behavior, but I haven't gotten around to re-implementing it.

**Comment by intrigus** [comment]
Okay, feel free to close this issue then!
