### ISSUE TITLE
Writing parsers for custom structs in define_language! macro

### ISSUE THREAD

**Issue by droidkid** [egraphs-good/egg#245]
I'm trying to write a custom parser for a language term that uses a struct that I have defined. 

Let's say I have a language defined as,
```rust
define_language! {
    pub enum DummyLang {
        Point2D(Point2D),
    }
}
```

where Point2D is 
```rust
#[derive(Debug, Clone, Hash, PartialEq, Eq, PartialOrd, Ord, Display, FromStr)]
#[display("(x:{x},y:{y})")]
pub struct Point2D {
    pub x: i32,
    pub y: i32,
}
```

Then the below line 
```rust
let exprViaString: RecExpr<DummyLang> = "(x:24,y:36)".parse().unwrap();
```
results in a `BadOp(FromOpError { op: "x:24,y:36", children: [] })',`

I setup a minimal example in a [repo](https://github.com/droidkid/egg-questions) with a [testcase](https://github.com/droidkid/egg-questions/blob/master/src/main.rs) showing that the parser for Point2D exists, but I'm not able to parse it to a RecExpr.

A sort of workaround I've been living with is to define Point2D as a list of Ids, like

```
define_language! {
  Num(i32),
  "point2D" = Point2D([Id; 2]) // (point2d 24 36) now parses.
}
```

But as you can imagine, this results in a lot of boilerplate in unpacking the ids when wanting to inspect Point2D, and it's easy to mess up the order of point2D args. 

(I have a feeling I'm missing something obvious, but my rust foo is not strong enough to figure it out.)

**Comment by droidkid** [comment]
Ahhhhh, that worked! Thank you for the quick response! I knew I was missing something obvious :/

**Comment by mwillsey** [comment]
:+1:
