### ISSUE TITLE
Getting the root ID of a RecExpr

### ISSUE THREAD

**Issue by droidkid** [egraphs-good/egg#246]
Once a RecExpr is extracted from a EGraph, how do I get the ID of the root node of the RecExpr

```rust
    let extractor = Extractor::new(&runner.egraph, CostFn);
    let (_cost, optimized) = extractor.find_best(id_to_rewrite);
    // I want to match on the root node of optimized RecExpr, how do I do that?
```

I have been relying on adding the optimized expression back to the egraph to get the ID, 
```rust
    let id = egraph.add_expr(&optimized);
    match optimized[id] {
          ....
    }
```
But that feels a bit clunky - and I'm not entirely sure it is always correct, is the Id of the extracted expression in the EGraph guaranteed to be the same as the Id of the root node in the RecExpr, and if so is it ok to rely on this behaviour?

A more practical use case of this is when extracting the expression of a substitution in a applier, something on the lines of 

```rust
let subs_expr = egraph.id_to_expr[ subst[self.field_captured_in_rewrite_rule] ]
// I'd like to explore the root node of subs_expr to inspect the values inside.
```

**Comment by mwillsey** [comment]
That cannot be relied on. The `Id`s in a RecExpr only refer to nodes in that `RecExpr`, it cannot be assumed that have meaning anywhere else. If you just want the operator at the root of it, you can use [`expr.as_ref()`](https://docs.rs/egg/latest/egg/struct.RecExpr.html#impl-AsRef%3C%5BL%5D%3E-for-RecExpr%3CL%3E) to get the slice of the e-nodes. The last one is the root.

**Comment by droidkid** [comment]
Ah, `expr.as_ref()` wasn't clear to me, but upon pointing it out this makes sense. Tried it out locally and it works.

Would a explicit `get_root_term() -> L` or something on that lines make sense for RecExpr? (Not needed, but would be helpful I feel, please feel free to close this issue)

**Comment by mwillsey** [comment]
`root(&self) -> &L` is a good idea. I would accept such a PR!
