### ISSUE TITLE
Randomly extract a RecExpr from a EGraph

### ISSUE THREAD

**Issue by ntcmp2u** [egraphs-good/egg#264]
Hi. Is there a simple way to implement an Extractor that can randomly extract a ``RecExpr`` that is equal to the initial expression of a EGraph? I hope that we can use this extractor like this:

```rust
let start = "(+ 0 (* 1 a))".parse().unwrap();
let runner = Runner::default().with_expr(&start).run(rules);

let extractor = RandomExtractor::new(&runner.egraph);
let equal_expr: RecExpr<Language> = extractor.randomly_find(runner.roots[0]);
```

I think it is a very useful function that can help us quickly obtain a equal expression without specifying a cost function. Could someone give me some hint that can implement this extractor in a simple way?

**Comment by mwillsey** [comment]
No, nothing is built in for this. The [`build_recexpr`](https://docs.rs/egg/latest/egg/trait.Language.html#method.build_recexpr) function might be useful to implement this instead of an extractor. Basically you could randomly pick an enode, call `build_recexpr` on it, and recurse.
