### ISSUE TITLE
Mutable access to the EGraph in `Analysis::make`

### ISSUE THREAD

**Issue by cole-k** [egraphs-good/egg#276]
Can we change the signature of `Analysis::make` as follows? I need to access my EGraph analysis mutably when I make an EClass analysis.

```diff
-    fn make(egraph: &EGraph<L, Self>, enode: &L) -> Self::Data {
+    fn make(egraph: &mut EGraph<L, Self>, enode: &L) -> Self::Data {
```

It seems to not have any problems locally.

The change required: https://github.com/egraphs-good/egg/compare/main...cole-k:egg:mutable-egraph-in-analysis-make

**Comment by cole-k** [comment]
I realize now that this may have been intentional to prevent screwing with the egraph during the analysis. My quandary is that I need mutable access to the EGraph analysis, any suggestions on how to resolve this? I don't mind writing some extra code.

**Comment by mwillsey** [comment]
Could you use a refcell?

**Comment by cole-k** [comment]
Yeah I think that works. I'll close this then.
