### ISSUE TITLE
How to implement complex rules for expression simplification?

### ISSUE THREAD

**Issue by yg0x01** [egraphs-good/egg#278]
I recently used Egg to simplify expressions in my project, which is really awesome. Thank you for creating such a cool tool.

I have a question. When I simplify expressions, we usually use AstSize or AstDepth to help us choose the best result. However, how can we implement more complex rules?

For example, the expression `(+ (+ x 1) (+ 2 y))` can be simplified to` (+ (+ x 3) y)`. However, if I want to simplify it to `(+ (+ x y) 3)`, that is, the right side of the outermost layer is a constant value.

I checked the source code and found that `cost_function` can only be calculated for a single enode. In this method, I cannot access other nodes. Do I have to customize an Extractor myself to implement more complex rules?

Thank you very much.

**Comment by yihozhang** [comment]
I don't think this is directly supported, but you can manually search for the pattern `(+ (+ ?x ?y) ?z)` and filter based on whether `?z` is a constant in the e-graph, manually compute the cost by querying the cost of each variable, to derive the optimal term.

FWIW, [Sketch-guided Equality Saturation](https://arxiv.org/pdf/2111.13040.pdf) does something similar to what you described, so it might be worth it to look into that paper.

**Comment by yg0x01** [comment]
> I don't think this is directly supported, but you can manually search for the pattern `(+ (+ ?x ?y) ?z)` and filter based on whether `?z` is a constant in the e-graph, manually compute the cost by querying the cost of each variable, to derive the optimal term.
> 
> FWIW, [Sketch-guided Equality Saturation](https://arxiv.org/pdf/2111.13040.pdf) does something similar to what you described, so it might be worth it to look into that paper.

Thanks for your help, I will try the method and article you mentioned
