### ISSUE TITLE
How to define `rewrite` if I have no idea of how many variable in expression

### ISSUE THREAD

**Issue by Gy-Hu-Star** [egraphs-good/egg#279]
For example, for `rewrite!("commute-mul"; "(* ?a 0)" => "0"),` It can easily rewrite `(* a 0)` to `0`. However, sometimes I have no idea of how many variable in s-expression, it may be dynamic, such as `(+ (* a 0) (* a b 0)` or `(+ (* a 0) (* a b c 0) `. As I can use `List(Box<[Id]>)` to handle parsing, I cannot find a way to define rewrite function that can handle `(* ?a 0)" => "0")` with `?a` can be any number of variable

**Comment by mwillsey** [comment]
egg does not support patterns of variadic length like that. You could implement a custom [`Searcher`](https://docs.rs/egg/latest/egg/trait.Searcher.html), or encode your problem in a different way.
