### ISSUE TITLE
How to pretty-print an egrah

### ISSUE THREAD

**Issue by ntcmp2u** [egraphs-good/egg#281]
I found the [pictures](https://egraphs-good.github.io/assets/egraphs.svg) drawn in the egg's paper and homepage are pretty. However, the ``egraph.dot().to_png()`` cannot produce such pictures. Could you tell me how to draw the picture in your paper from the dot file? which command line for ``dot`` you used?

**Comment by mwillsey** [comment]
They were not generated automatically. I drew them by hand using [draw.io](https://app.diagrams.net/).

You can see the drawio file here: https://github.com/egraphs-good/egg/tree/main/doc
