### ISSUE TITLE
Is possible to use egg with my own parser as *input* instead of using text?

### ISSUE THREAD

**Issue by mamcx** [egraphs-good/egg#292]
I have my own parser, with AST, a pretty printer, better errors, etc.

Then I wish to feed into egg for rewrites and simplifications.

For example:

```rust
    enum Token {
        Add,
        Mul,
        If(Box<Token>, Box<Token>, Box<Token>)
    }

    define_language! {
        enum SimpleLanguage {
            Num(i32),
            Token::Add = Add([Id; 2]),
            Token::Mul = Mul([Id; 2]),
            Symbol(Symbol),
        }
    }
```

but this does not look possible? It looks like the ideal use case for egg is to be part of the middle layer in a parser pipeline...

**Comment by mwillsey** [comment]
egg can't work with recursive data structures like your AST, it needs to be able to unpack everything and know about the structure (hence the `Id` types everywhere). However, you don't need to use the `define_language` macro if you don't want to, you can implement all the traits that it implements manually. You will need to de-recursive-ify your AST type into something with `Id`s though, and at that point the `define_language` macro is probably useful.

**Comment by mamcx** [comment]
Ok, I expand the macro and see the way to manually implement it, but how get to`..and at that point the define_language macro is probably useful.`?

Do you mean the AST should be:


```rust
 enum Token {
        Add([Id; 2]),
        Mul([Id; 2]),
        If(Id, Id, Id)
    }
```

**Comment by mwillsey** [comment]
Correct, your AST will have to look like that. And at that point, the `define_language` macro is basically what you want. Even if you use the macro, there is nothing stopping you from manually constructing terms and rewrite rules if you'd rather not use the parsing.

**Comment by mwillsey** [comment]
Closing for now, feel free to re-open if needed!
