### ISSUE TITLE
How to simplify multiple equations with the same variables?

### ISSUE THREAD

**Issue by Flians** [egraphs-good/egg#295]
Dear,

When I have multiple equations with the same variables, how can I simplify them using egg.
Since I noticed that there is only one root in E-Graph, multiple equations need multiple roots.
Such as, `y_1= (a+b) * c` and `y_2= (a+b) * d` share the item `(a+b)`.

Could you please supply some suggestions about this problem?
Thank you.

**Comment by yihozhang** [comment]
Does `multi_rewrite!` work for your case? See (`datalog.rs`)[https://github.com/egraphs-good/egg/blob/main/tests/datalog.rs#L66] for an example.

**Comment by Flians** [comment]
Many thanks for the prompt reply.
`multi_rewrite` may be not suit for my problem. It can support the transformation from multiple patterns to a new pattern. However, what I wanna is to simultaneously rebuild multiple input equations sharing the same variables.

**Comment by yihozhang** [comment]
Oh I misread your problem. There is no restriction on how many roots an E-graph can have. A root E-class is just a normal E-class, and as you can see, the `roots` field of [`Runner`](https://docs.rs/egg/latest/egg/struct.Runner.html) is a `Vec`. Could you elaborate more on where you cannot have multiple roots? Maybe you are talking about limitations of a specific API?

**Comment by Flians** [comment]
Thank you very much. I have got it. Actually, now I wanna use the Equality Saturation to solve my problem. Maybe I will give you feedback after done. Thank you again.
