### ISSUE TITLE
Division by zero nitpick - docs

### ISSUE THREAD

**Issue by memoryleak47** [egraphs-good/egg#297]
Thanks for the excellent crate!

I have a nitpick about an example in the docs. Feel very free to close this, if deemed a non-issue.
The example provided in https://docs.rs/egg/0.9.5/egg/macro.rewrite.html implements a division by zero check as follows:

```
fn is_not_zero(var: &'static str) -> impl Fn(&mut EGraph, Id, &Subst) -> bool {
    let var = var.parse().unwrap();
    let zero = SimpleLanguage::Num(0);
    move |egraph, _, subst| !egraph[subst[var]].nodes.contains(&zero)
}
```

If I'm not missing anything, this check might be incomplete.
The `is_not_zero` function might return `true`, if the egraph has not yet determined that the input term simplifies to zero.
This wouldn't catch division by terms like `(- 1 1)`, if the rewrite rules are executed in an unlucky order,
and thus lead to potentially incorrect results.

**Comment by mwillsey** [comment]
You are absolutely correct! It's just a demonstration of how to use the conditional functionality though. Perhaps a comment should clarify this.
