### ISSUE TITLE
Loss of the discussions tab and its content

### ISSUE THREAD

**Issue by SamPruden** [egraphs-good/egg#302]
The Discussions tab was previously active on on this repo and contained some useful resources, tips, and tricks for working with `egg`. It appears to have disappeared and those resources along with it, although some of them are still showing up in google results for now (and 404ing).

Perhaps it was taken down for good reason, but I'd encourage those discussions to be restored if possible - even if you point people to the zulip for new discussions! Or alternatively, perhaps they could be archived somewhere.

**Comment by mwillsey** [comment]
Okay! I've restored them but pinned a message to use zulip instead.
