### ISSUE TITLE
Question: Dealing with side effects/assignment

### ISSUE THREAD

**Issue by thorstenhater** [egraphs-good/egg#304]
Hi,

I am new to the topic of eGraphs, but it looks like an interesting intermediate step for a project
of mine, an optimising DSL compiler handling systems of ODEs. My problem is now that this
DSL has --- for historic reasons that mean I cannot eliminate them  --- side effects like 
assignment and for-loops. Is there a way to still use eGraphs and egg specifically and how would
that like look like?

An example, possibly based on the lambda-test, would be appreciated.

**Comment by mwillsey** [comment]
That is an area of open research. The original equality saturation paper
[1] could be helpful to you, but the answer is basically that you have to
come up with an encoding that is pure, and doing so from an imperative
language can lead to a complex encoding/decoding.

[1]: https://arxiv.org/abs/1012.1802

**Comment by thorstenhater** [comment]
I'll look more into the paper, thanks, but that confirms what I feared to find. A quick search though brings up Peggy
> Peggy operates on the entire Java bytecode instruction set, complete with side
effects, method calls, heaps, and exception

which seems to indicate that it should be possible. But I guess not in `egg`, then.

I'd see a way forward if one could either build eGraphs on SSA form or alternatively attach attributes to variable (essentially
whether I can prove that they are never mutated). The former requires handling phi-nodes (which I don't see how) and the 
latter I haven't seen as possible either, yet.

**Comment by mwillsey** [comment]
Peggy is the tool in that paper. It "handles" side effects etc by encoding
JVM bytecode into a pure, referentially transparent format called PEGs
(program expression grammar). This encoding (and the corresponding
decoding) is non-trivial, and requires lots of machinery on either side to
get to/from a CFG. You can kind of think of PEGs and SSA++ they convert not
only basic blocks into a dataflow-like construct, but the control as well.

**Comment by thorstenhater** [comment]
Thanks, I'll see if I can can make it work via CPS since that seems
enough to handle assignment specifically.
