### ISSUE TITLE
Map from `EGraph<L, _>` to `EGraph<L2, _>`

### ISSUE THREAD

**Issue by sgpthomas** [egraphs-good/egg#305]
I want to use the [babble](https://github.com/dcao/babble) library with an e-graph that I own. `babble` expects an EGraph over the `AstNode<Op>` (which implements `egg::Language`) type. I have an EGraph over my own language type, let's call it `Lang`, and it's trivial to write a function from `Lang -> AstNode<Op>`. However, as far as I can tell, there is not a good way to lift this into a function `EGraph<Lang, _> -> `EGraph<AstNode<Op>, _>`. Am I missing something in the library, or do you have a recommendation for how to do this?

**Comment by mwillsey** [comment]
Closed by #306
