### ISSUE TITLE
Avoid recursive rule applying during Runner::run()

### ISSUE THREAD

**Issue by ChijinZ** [egraphs-good/egg#307]
Hi, I'm new to egg. I'm wondering if I can avoid recursively applying rule during quality saturation.

For example, let's say I have a rule ``x -> neg(neg(x))``. My goal is to prevent the output of this rule from being applied again, which would potentially lead to an infinite egraph like ``neg(neg(neg(neg(... (x)))))``.

I'm wondering what would be the best way to achieve this goal in egg. Would it be feasible if I include a specific condition when writing this rule to prevent its recursive application? Or is there a built-in mechanism in egg that can handle this situation?

**Comment by mwillsey** [comment]
For that particular rule, I don't think that it should result in an infinite e-graph. It potentially could if combined with other rules, but by itself it should just create a cycle in the e-graph which represents infinite terms. There is not a built-in mechanism to avoid such cycles.

**Comment by ChijinZ** [comment]
Thanks for your answer!
