### ISSUE TITLE
Bad explanation when using explain existance

### ISSUE THREAD

**Issue by eytans** [egraphs-good/egg#316]
I was seeing weird results so I wrote the following test:

```rust
#[test]
fn simple_explain_exists() {
    //! Same as previous test, but now I want to make a rewrite add some term and see it exists in
    //! more then one step
    use crate::{EGraph, SymbolLang};
    crate::init_logger();

    let rws: Vec<Rewrite<SymbolLang, ()>> = [rewrite!("makeb"; "a" => "b"), rewrite!("makec"; "b" => "c")].iter().cloned().collect();
    let mut egraph = Runner::default().with_explanations_enabled()
        .with_expr(&"a".parse().unwrap())
        .run(&rws).egraph;
    let mut exp = egraph.explain_existance(&"c".parse().unwrap());
    assert_eq!(exp.make_flat_explanation().len(), 3, "Expected 3 steps, got {:?}", exp.make_flat_explanation());
}
```

The explanation I get is
a
c (makec)

So I believe something is amiss. I'll try to look into it, but thought it's better to put it out there for now
@oflatt  I am guessing you are the right person to tag here

**Comment by oflatt** [comment]
That does look like a problem!
I think the existence code is much less well-tested than the code for getting an explanation for why two things are equal.
Let me know if you find a solution!
