### ISSUE TITLE
egg ignore a comm rule

### ISSUE THREAD

**Issue by asukaminato0721** [egraphs-good/egg#323]
https://github.com/asukaminato0721/egg-integral/blob/21b0146dae15d9118bfa61ee6f9890354401a98e/src/main.rs#L335

```rust
            "(* (ln x) (sqrt x))",
            "(* (sqrt x) (ln x))", // this not work
```

but there is already `    rw!("comm-mul";  "(* ?a ?b)"        => "(* ?b ?a)"),`

**Comment by yihozhang** [comment]
Could you elaborate a bit more on what the expected behavior here is?

**Comment by mwillsey** [comment]
I'm not sure exactly what's going on, but your example can prove false if you crank up the node limits a bit (especially if you use the `SimpleScheduler`, which I would recommend as it's more predictable). I suspect it's due to your `is_not_zero` being unsound; it only checks for syntactic equivalence to zero, which is insufficient because something could "become" zero later (for example `x/x - 1` isn't zero right now, but will eventually be rewritten to zero).

**Comment by asukaminato0721** [comment]
> Could you elaborate a bit more on what the expected behavior here is?

it's a symbolic integrator, and since there are `comm-mul` rule, so 

```
int   (* (ln x) (sqrt x)) dx
int   (* (sqrt x) (ln x)) dx
```

should behave the same.

The first line calculated successfully.

```
running 1 test
[src/main.rs:349:13] best_expr.to_string() = "(- (* (ln x) (* (^ x 3/2) 2/3)) (* 2/3 (* (^ x 3/2) 2/3)))"
[src/main.rs:350:13] runner.explain_equivalence(&start, &best_expr).get_flat_strings() = [
    "(i (* (ln x) (sqrt x)) x)",
```

But the second line failed.

```
[src/main.rs:349:13] best_expr.to_string() = "(i (* (sqrt x) (ln x)) x)"
[src/main.rs:350:13] runner.explain_equivalence(&start, &best_expr).get_flat_strings() = [
    "(i (* (sqrt x) (ln x)) x)",
]
[src/main.rs:354:13] MathCostFn.cost_rec(&best_expr) = 106
```

the github action log is here.

[logs_26308394695.zip](https://github.com/user-attachments/files/16355106/logs_26308394695.zip)

**Comment by asukaminato0721** [comment]
> I'm not sure exactly what's going on, but your example can prove false if you crank up the node limits a bit (especially if you use the `SimpleScheduler`, which I would recommend as it's more predictable). I suspect it's due to your `is_not_zero` being unsound; it only checks for syntactic equivalence to zero, which is insufficient because something could "become" zero later (for example `x/x - 1` isn't zero right now, but will eventually be rewritten to zero).

this function is adapted from https://github.com/egraphs-good/egg/blob/347326d2e8ebbacca12d8e1398b86eff6dcfb2c5/tests/math.rs#L135-L145

and I am not sure how to fix this.

---

oh, I fix this.

```rs
                .with_scheduler(BackoffScheduler::default().with_initial_match_limit(3000))
```

I need to up the match_limit
