### ISSUE TITLE
Improve benchmarking with criterion

### ISSUE THREAD

**Issue by paulzzy** [egraphs-good/egg#331]
Hello! I'd like to make egg's benchmarking more rigorous and easier to modify. I'm considering Criterion because it seems to be the de facto standard for benchmarking in Rust projects. Before making a pull request, I wanted to make sure this kind of change would be okay. Is there anything I'm missing?

**Comment by mwillsey** [comment]
I think the bigger problem is with the lack of data for the benchmarks, as the existing ones are rather contrived. Is using criterion something that would be useful to you? egg is in a pretty stable period of lower-paced development atm.

**Comment by paulzzy** [comment]
There's a change I'd like to make that should result in a performance improvement and I'm interested in measuring it accurately (related to rules that "explode" the e-graph).

> the existing ones are rather contrived

Do you mean that existing benchmarks are insufficient? Or that the math.rs and lambda.rs benchmarks measure contrived use cases?

**Comment by yihozhang** [comment]
I think one reason why the current math.rs and lambda.rs are not sufficient is they are too small to reflect realistic workload. For instance, I would expect the performance improvement from https://github.com/egraphs-good/egg/pull/61 to not be that big in many cases in practice because the bottleneck is usually e-matching instead of rebuilding when the e-graph gets bigger. I think it would be valuable to consider a more standardized/bigger benchmark like https://github.com/yihozhang/egg-smol-benchmark before using more serious benchmarking tools.

**Comment by paulzzy** [comment]
Thanks for sharing! From a cursory look it seems to use the same tests as math.rs, what's different about it?

> I think it would be valuable to consider a more standardized/bigger benchmark

Egg is used in projects like Herbie and Cranelift. Would it be worthwhile to try creating benchmarks out of their test suites?

**Comment by yihozhang** [comment]
Not very different from math.rs but it's bigger. IIRC it uses basically the same ruleset as math.rs, but runs it for more iterations, and removes some conditional rules. 

> Egg is used in projects like Herbie and Cranelift. Would it be worthwhile to try creating benchmarks out of their test suites?

Herbie is very similar to math.rs, and I don't think Cranelift uses egg? But I agree it's a good idea to create benchmarks out of rulesets from [existing applications](https://necessary-taker-84c.notion.site/Projects-that-use-equality-saturation-9b298720aa724f8b8a72001398e88d9f).

**Comment by paulzzy** [comment]
Thanks for the list!! Oh yeah Cranelift has a custom implementation but I vaguely recall seeing egg in their Cargo.toml.

For now I'll finish up my other change; I've actually seen performance improvements even with the current benchmarking harness, but I'll consider using an existing application if I need the rigor.
