### ISSUE TITLE
Add `&mut self` parameter to all Analysis functions

### ISSUE THREAD

**Issue by KarelPeeters** [egraphs-good/egg#335]
Currently the [`Analysis` trait](https://docs.rs/egg/latest/egg/trait.Analysis.html) is defined as follows:

```rust 
pub trait Analysis<L: Language>: Sized {
    type Data: Debug;

    // Required methods
    fn make(egraph: &EGraph<L, Self>, enode: &L) -> Self::Data;
    fn merge(&mut self, a: &mut Self::Data, b: Self::Data) -> DidMerge;

    // Provided methods
    fn pre_union(
        egraph: &EGraph<L, Self>,
        id1: Id,
        id2: Id,
        justification: &Option<Justification>
    ) { ... }
    fn modify(egraph: &mut EGraph<L, Self>, id: Id) { ... }
}
```

There is some inconsistency here: of the 4 functions, only `merge` takes any form of `self` as a parameter. This makes it impossible to pass any sort of settings, configuration, state, ... though the `Analysis` struct definition.

I suggest that `&mut self` should be added as a parameter to the 3 remaining functions. I had a quick look though the code, and didn't immediately see a use site that would be unable to pass it.

If this change is okay let me know, then I can submit a PR for it.

**Comment by mwillsey** [comment]
The `EGraph` contains the analysis itself as a public field: https://docs.rs/egg/latest/egg/struct.EGraph.html#structfield.analysis

So receiving the e-graph is a superset of receiving just the analysis. If anything, the change should go the other way (make `merge` receive the whole e-graph), but I'm not willing to change that API at this time unless there is compelling need.

**Comment by KarelPeeters** [comment]
I missed that, thanks!
