### ISSUE TITLE
unique node counting

### ISSUE THREAD

**Issue by Flians** [egraphs-good/egg#338]
Hi, when I define `egg::CostFunction`, I want to count unique nodes. 
But I met the following problem:
For `(* (+ a b) (+ a b))`, using `AstSize` will output that the node size is 3. But the results of two `(+ a b)` are the same and should be from the same node. So, I hope the node size is 2. Could you please tell me how to achieve it? Thank you.

**Comment by mwillsey** [comment]
This is a hard problem, and requires heavy weight techniques. See below:

- https://docs.rs/egg/latest/egg/struct.LpExtractor.html in egg right now
- better algorithms in development https://github.com/egraphs-good/extraction-gym
- https://www.cs.princeton.edu/~dh7120/assets/papers/EGRAPHS2023.pdf for a more formal explanation
