### ISSUE TITLE
Build error using `nightly` toolchain

### ISSUE THREAD

**Issue by bksaiki** [egraphs-good/egg#339]
`egg` is not building on the `nightly` toolchain (1.84+). This is due to `stdsimd` being removed in February; `ahash` has since been updated but `egg` is using an old version of `ahash`.

<img width="1437" alt="build-failure" src="https://github.com/user-attachments/assets/8992d1a2-d29d-40e9-8213-593517c5f7e3">

**Comment by mwillsey** [comment]
Which toolchain exactly are you using? This works for me.

```sh
% cargo +nightly version
cargo 1.85.0-nightly (66221abde 2024-11-19)
% cargo +nightly build  
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.02s
```

**Comment by mwillsey** [comment]
Okay, I just tried and `cargo update` fixes this. Run that to update the `egg-herbie`'s locked dependencies.
