### ISSUE TITLE
nits in lambda test

### ISSUE THREAD

**Issue by remysucre** [egraphs-good/egg#57]
I think there are some nits in the lambda test. For example, `Analysis::make` inserts the ID of *variables* to `free`, but `lambda` takes a *symbol* and `CaptureAvoid::apply_one` tests if that symbol is in `free`, which will always be false. To see this, changing `lambda_capture_free` to the following will fail: 

```
 egg::test_fn! {
    #[should_panic(expected = "Could not prove goal 0")]
    lambda_capture_free, rules(),
    "(let y (+ (var x) (var x)) (lam (var x) (var y)))" => "(lam (var x) (+ (var x) (var x)))"
}
```

Similarly, the test cases also pass symbols to `let` and `fix`, which `Analysis::make` would add to `free`. 

Furthermore, in my implementation I consistently use variables instead of symbols, but implementing the free variable test as in `CaptureAvoid` does not work. The ID of `v2` never matches any ID stored in `free` (any clue why this happens? Do I have to call `find`?) Instead, I had to test if the free var of `v2` is in the free vars of `e`.

**Comment by remysucre** [comment]
Oops sorry, I confused myself. `free` does indeed contain symbol IDs.

**Comment by mwillsey** [comment]
Yeah, this would look nicer if you could have different sorts or something. Like, it's really unintuitive that its Lambda([Id; 2]) instead of Lambda(Symbol, Id).
