### ISSUE TITLE
Language must be an enum

### ISSUE THREAD

**Issue by bjchambers** [egraphs-good/egg#67]
Noticed this when trying to use a generic language like:

```
struct MyLang {
  op: OpKind,
  children: Vec<Id>,
}
```

When used as a pattern, `search` fails because it uses `std::mem::discriminant(...)` to get the key of the enum, which is unspecified behavior.

This restriction should at least be documented, since it affects the set of valid languages.

One suggestion would be to add something to the `Language` trait that allows the user to change the discriminant. In my case, the `OpKind` could be used to identify operators.

For instance:

```
trait Language {
  type OpDiscriminant: PartialEq + Eq + Hash + Debug;
  fn discriminant(&self) -> OpDiscriminant
}
```

For languages that based on enums, this could be implemented as:

```
impl Language for EnumLang {
  type OpDiscriminant = Discriminant<Self>;
  fn discriminant(&self) -> OpDiscriminant { std::mem::dicriminant(self) }
}
```

For languages like mine that use a struct, this could be:

```
impl Language for MyLang {
  type OpDiscriminant = OpKind;
  fn discriminant(&self) -> OpDiscriminant { self.op }
```

I'm not sure if this affects other parts of the code. If not, I'd be happy to try creating a pull request to address this if the approach outlined above seems reasonable.

**Comment by mwillsey** [comment]
Hmmm, yeah the discriminant thing was a definite hack. We are working on a new e-matching procedure that won't rely on this at all. In fact it looks a lot like what you're doing: `Language` will probably gain an `Operator` associated type that allows you to split things up.

I didn't expect it to break non-enum languages though. What does it return? I understand that it's unspecified, but it's not total UB I think. Everything should be fine as long as it returns a constant for structs, right?

**Comment by bjchambers** [comment]
I think when I stepped through it was retuning something that caused the
pattern to not match. I can try to make a smaller test case and share it.

Any idea on timing for the new matching?

**Comment by mwillsey** [comment]
Hopefully soon. It's the next feature I'd like to add to egg. For now, feel free to fork and use the approach you described. You could also just make your `struct` an `enum`:
```rust
enum MyLang {
  Only {
    op: OpKind,
    children: Vec<Id>,
  }
}
```

That will at least allow things to work. I'll try to remember to update this issue as soon as we get a branch up with the new e-matching.

**Comment by bjchambers** [comment]
Ok, did some more digging, and I think this can be closed (possibly in favor of an issue to track the work you mention).

1. For a struct, it looks like the discriminant will always be 0. IIUC, this will at-worst affect the performance (causing `egg` to consider more nodes than necessary). Is that correct?
2. The specific issue I was seeing (patterns not matching) seem to be a potential bug / misleading example from the tutorial:

https://docs.rs/egg/0.6.0/egg/tutorials/_02_getting_started/index.html#searching-an-egraph-with-patterns

Specifically, it looks like you need to call `rebuild` after calling `add` in order for the pattern to match. Specifically, I had an expression that was `(+ 5 0)` that *should* have matched `(+ ?x 0)` but it didn't. I mis-diagnosed this as related to the discriminant, but after adding a `rebuild` before trying to match the pattern it worked.

Maybe the example and documentation of `add` / `rebuild` could be updated to reflect this?
