### ISSUE TITLE
Other types of searchers and appliers

### ISSUE THREAD

**Issue by dylanede** [egraphs-good/egg#69]
The main one I can think of is an applier that adds a new expression based on a matched pattern, but does not substitute it (i.e. doesn't `union`). Instead it's just appended to the e graph as is. This could be used to create "deductions" that could then be used by conditional rewrite rules. Consider the use case of inferring properties of expressions based on the properties of their constituents. For example, a commutativity rewrite rule might be conditional on whether the operator in question is indeed commutative on the operands. The language might include set-theoretic terms like `x is-a-member-of N` which can be checked for with a condition so that the term `(x + y) is-a-member-of N` can be generated, and then the commutativity substitution `(x + y) + x` to `x + (x + y)` can be made.

I'm not sure how much this overlaps with the "analysis" feature, but it seems like it would be more powerful.

**Comment by mwillsey** [comment]
You can do just that! You can implement your own `Applier`, and it doesn't have to return anything to be `union`ed. It's free to manipulate the e-graph however you wish. The ConditionEqual struct does this:
https://github.com/egraphs-good/egg/blob/ea0c8f4cf26616a3c573286b436e7c329c74d39d/src/rewrite.rs#L418
https://docs.rs/egg/0.6.0/egg/struct.ConditionEqual.html

**Comment by dylanede** [comment]
Thanks for getting back to me! I have indeed implemented my own Applier for this (I've called it `Deduction`).
Next thing I wanted was to have multiple patterns as input (à la #39), so I tried to figure out how to make a Searcher that can do that. Unfortunately it looks like it's limited by having to return `SearchMatches`, which doesn't seem suitable for describing multi-matches. I'm wondering whether `SearchMatches` should be altered to cover this case, or whether it should become an associated type of `Searcher` and `Applier`. Going down the associated type route is a bit tricky to reconcile in the implementation of `Rewrite` and everything that depends on that (mainly `RewriteScheduler`). Not sure what your plans are for that?

Another customer searcher I was thinking of is something for searching within a scope - i.e. look for a pattern within a matched variable of another pattern. This would also require a different `SearchMatches` to express the substitutions in the inner and outer scope. It really does seem like making `SearchMatches` an associated type would be the best way forward.

**Comment by mwillsey** [comment]
Multi-patterns are one of the next things I'd like to implement, so that will hopefully be coming soon. Right now, the "workaround" is to just roll it yourself, unfortunately.

Can you say more about the second case? "i.e. look for a pattern within a matched variable of another pattern". Can you give an example?

**Comment by dylanede** [comment]
I don't have a concrete example right now but I'll come back with one once I get to that point.
