### ISSUE TITLE
Expand documentation on how to properly implement the Analysis trait

### ISSUE THREAD

**Issue by fabric-and-ink** [egraphs-good/egg#72]
I am struggling to implement the `Analysis` trait correctly, especially the `merge` function. I got very good at producing endless loops or failing asserts in the caller function. I have something working now for a very simple data type but I am not certain why it works. There are more elaborate examples in the paper and also some explanation, but I am still struggling. Also in the main branch the return value is now `Option<Ordering>` but I am not sure what is happening exactly depending on the respective four different results.

Please consider to add a bit more information there what invariants need to hold in the merge operation and what is happening when this function is called.

**Comment by mwillsey** [comment]
Yeah sorry about that, I plan to do this before releasing this version. The paper refers to the 0.6 version of egg, which uses a different type for the merge methods.

The docs on the method currently are here: https://github.com/egraphs-good/egg/blob/f94767cbf154ea2d89c83722a22b1a03aaf41e95/src/language.rs#L512-L522

Another way to frame this is that `merge` should return the partial ordering of the inputs `a` and `b`, and it should make `a` the join of `a` and `b`. The ordering should correspond to comparing `a` with `b` before you modified `a`.

**Comment by fabric-and-ink** [comment]
Ok, that is more clear! Thank you for explaining. If you don't mind, I can add your explanation in a PR.

**Comment by mwillsey** [comment]
Sure! That would be great!
