### ISSUE TITLE
Accessing analysis data after extraction

### ISSUE THREAD

**Issue by bjchambers** [egraphs-good/egg#78]
In some cases it would be useful to access the analysis data after extraction. For instance, the analysis data may include information about constraints or type information that are useful during rewriting (for instance, only apply certain rules to certain types of nodes). This information may also be useful for lower level code-generation from the extracted expression.

But, the extracted Ids are not related to the IDs in the graph, making the analysis information difficult to access.

Some possible options:
1. A variant of extraction (`extract_with_analysis`) that collects the analysis information for each node added to the `RecExpr`.
2. A map from IDs in the expression to IDs in the class. This seems error prone since the IDs could get mixed up.

I think the former would be pretty easy to add, if I'm reading things right:

```
    /// Find the cheapest (lowest cost) represented `RecExpr` in the
    /// given eclass.
    pub fn find_best_analysis(&mut self, eclass: Id) -> (CF::Cost, RecExpr<L>, Vec<N::Data>) {
        let mut expr = RecExpr::default();
        let mut data = Vec::new();
        let (_, cost) = self.find_best_analysis_rec(&mut expr, &mut data, eclass);
        (cost, expr, data)
    }

    fn find_best_analysis_rec(&mut self, expr: &mut RecExpr<L>, data: &mut Vec<N::Data>, eclass_id: Id) -> (Id, CF::Cost) {
        let eclass = self.egraph[eclass_id];
        let (best_cost, best_node) = match self.costs.get(&eclass.id) {
            Some(result) => result.clone(),
            None => panic!("Failed to extract from eclass {}", eclass.id),
        };

        let node = best_node.map_children(|child| self.find_best_rec(expr, child).0);
        data.push(eclass.data.clone());
        (expr.add(node), best_cost)
    }
```

It may be cleaner to create a wrapper around the data that allows indexing with `Id`.

Did I miss a way to get the analysis data after extraction? If not, would the above method be generally useful? Another option would be to allow the recursive call to take a function that is applied to each `eclass`. Then one version does nothing (and hopefully gets compiled away) while the other version pushes the data to the vector. This could also allow for versions that push just a part of the data, etc.

**Comment by mwillsey** [comment]
Since an extracted term is represented in the egraph, you could look it up and get it's e-class. Would that work?

**Comment by bjchambers** [comment]
Maybe? I would guess that it may be slightly slower (I'm guessing one or more hash-lookups of the RecExpr and it's arguments in order to find the node in the egraph), right?

But I don't just need the analysis of the RecExpr, I would want it for each of the children (and each of the children), etc. If I understand correctly, each of those would require some manipulation (to get the RecExpr corresonding to a specific child) and then a separate lookup, correct?

**Comment by mwillsey** [comment]
Would adding something this work better:
```rust
    pub fn find_best_node(&mut self, eclass: Id) -> L {
        self.costs[&self.egraph.find(eclass)].1.clone()
    }
```

Just trying to think what the simplest, most general thing I can add is.

**Comment by bjchambers** [comment]
I'm not sure I'm reading that right -- at first I thought it would be a mapping from the `Id` in the `RecExpr` to the `Id` in the original `egraph`, but it seems like it may be going the other direction?

I guess if the `Extractor` allowed mapping each Id of the `RecExpr` to the eclass ID that would work, because I could then lookup the original data. The only concern then being the potential for error (since the `Id` for the `RecExpr` isn't the same as the `Id` in the `egraph`, correct?). If such a mapping were possible it would address the need to access data from the sub-parts of the extracted expression.

The safety could maybe be addressed separately by using some kind of phantom type so it is clear the IDs from the `RecExpr` are associated with the `RecExpr`.

**Comment by mwillsey** [comment]
This should be resolved by that commit. Feel free to reopen if it doesn't!

**Comment by bjchambers** [comment]
I think that'll work! Thanks for the quick response!
