### ISSUE TITLE
What happened to Language::children()?

### ISSUE THREAD

**Issue by rosekunkel** [egraphs-good/egg#80]
This method was present in the latest release but no longer exists in the development version. I don't see anything in the changelog about it. I have the same question about `Language::children_mut()`.

**Comment by mwillsey** [comment]
Yeah I removed them at some point because I had big plans where I didn't want to force children to be in a slice. We can probably put those back.

**Comment by mwillsey** [comment]
It's kind of a pain to have the `define_language!` macro generate them tho. Do you have a use case that's not covered by the provided combinators.

Also, I should add that to the unreleased changelog. My bad.

**Comment by rosekunkel** [comment]
I had some code that was iterating over `enode.children().iter()`. I worked around it by making a `Vec` and adding all the children to it using `Language::for_each`. Is there a reason `Language` has a bunch of combinators instead of just `iter()`, `iter_mut()`, and `into_iter()`?

**Comment by mwillsey** [comment]
I was hoping to support an enum branch that looks like `Add(Id, Id)` instead of `Add([Id; 2])`. And you can't assume the former is a slice. And implementing iter for that would be tricky IMO.

**Comment by rosekunkel** [comment]
It would be easier to add things like that `define_language!` was a procedural macro. Would you be interested in a pull request implementing that?

**Comment by mwillsey** [comment]
That would be great! That’s been on my stack for a while, but it’s always been easier to just hack the macro_rules more :)

**Comment by rosekunkel** [comment]
Ok, I'll give it a shot.

**Comment by rosekunkel** [comment]
@mwillsey I have an idea for how to add iterators over the children to the `Language` trait. Would a pull request that replaces the existing combinators with standard `iter`/`iter_mut`/`into_iter` be welcome?

Also, re: `Add(Id, Id)`, I would expect the iterator in that case to be something like this:
```rust
match node {
    Add(x, y) => [x, y].into_iter()
    // ...
}
```

**Comment by mwillsey** [comment]
Honestly we should probably just put children back for now. I don’t see the proc macro happening for a while, especially with other pattern matching changes coming in soon.

**Comment by mwillsey** [comment]
Sorry didn’t mean to close. If you’ve got time to PR this, I’d take it. I can do it too

**Comment by rosekunkel** [comment]
Do you mean you'd take the `Iterator` version? Or just putting `children` back?

**Comment by mwillsey** [comment]
Just putting children back, im doing it rn.

**Comment by mwillsey** [comment]
Do really pile on this issue. Im starting to thing we should go alllll the way back to separating the e-node into operator and children. But we can experiment with that later.

**Comment by rosekunkel** [comment]
I've been experimenting with something like that already actually -- currently it looks something like this:
```rust

trait HasChildren<'a> {
    type IterChildren: Iterator<Item = Id>;
    type IterChildrenMut: Iterator<Item = &'a mut Id>;

    fn children(&'a self) -> Self::IterChildren;
    fn children_mut(&'a mut self) -> Self::IterChildrenMut;
}

trait ENode: for<'a> HasChildren<'a> {
    type Operator: Eq;
    type Children: IntoIterator<Item = Id>;

    fn from_parts(operator: Self::Operator, children: Self::Children) -> Self;
    fn into_parts(self) -> (Self::Operator, Self::Children);
    fn as_operator(&self) -> Self::Operator;
}
```

**Comment by rosekunkel** [comment]
Should I make a separate issue to discuss that idea?

**Comment by mwillsey** [comment]
That’s really interesting! I think we would need to compare the approaches some more, so a new issue sounds good. I’ll close this with my commit later.
