### ISSUE TITLE
Non-enum Languages significantly slower

### ISSUE THREAD

**Issue by bjchambers** [egraphs-good/egg#82]
I created a copy of the `math.rs` test that uses a custom language based on a struct:

```
#[derive(Clone, Debug, Hash, PartialEq, Eq, PartialOrd, Ord)]
enum MathOp {
    // 2 args
    Diff,
    Integral,
    Add,
    Sub,
    Mul,
    Div,
    Pow,
    // 1 args
    Ln,
    Sqrt,
    Sin,
    Cos,
    // 0 args
    Constant(Constant),
    Symbol(Symbol),
}

#[derive(Clone, Debug, Hash, PartialEq, Eq, PartialOrd, Ord)]
pub struct Math {
    op: MathOp,
    children: Vec<Id>,
}
```

Running the benchmarks shows this to take 15-30% more cycles for each test:

Test|math|math_struct|math / math_struct|1-(math / math_struct)
----|----|-----------|------------------|----------------------                                                            
diff_power_harder|21,074,499|30,392,699|69.34%|30.66%
diff_power_simple|5,047,100|7,156,238|70.53%|29.47%
integ_one|1,329,639|1,533,784|86.69%|13.31%
integ_part1|8,189,299|12,439,484|65.83%|34.17%
integ_part2|30,383,957|48,027,206|63.26%|36.74%
integ_part3|3,705,544|5,267,235|70.35%|29.65%
integ_sin|1,340,420|1,547,473|86.62%|13.38%
integ_x|1,401,729|1,639,932|85.47%|14.53%
associate_adds|60,466,286|80,325,970|75.28%|24.72%
diff_different|1,337,645|1,543,119|86.68%|13.32%
diff_ln|1,350,054|1,556,474|86.74%|13.26%
diff_same|1,321,303|1,498,483|88.18%|11.82%
diff_simple1|3,352,771|4,654,982|72.03%|27.97%
diff_simple2|3,018,403|4,165,698|72.46%|27.54%
powers|1,440,284|1,731,722|83.17%|16.83%
simplify_add|2,648,652|3,418,225|77.49%|22.51%
simplify_const|1,746,411|2,237,483|78.05%|21.95%
simplify_factor|8,295,182|11,505,095|72.10%|27.90%
simplify_root|11,303,834|15,622,872|72.35%|27.65%

1. It seems like the performance shouldn't be this much worse, since the operator can still be extracted and used as a key.
2. In some cases, it seems like it should be even *faster*, since the constant or symbol can be part of the operator key, filtering out more cases (especially for 0 / 1 constants).

I suspect the problem is the use of `discriminant`, which causes all nodes to be considered the same, preventing short-circuiting of some searches and possibly inability to use lookup classes by operator, etc.

As a first step, I can send a PR with the test / benchmark. I think @mwillsey you had mentioned some planned work that would address this, so perhaps this issue can just serve as a tracking issue for that work?

This would be helpful (and avoid surprises) in cases where egg is being used as part of a larger project that already has a language defined.

**Comment by mwillsey** [comment]
I think the issue here is actually just using `Vec`. E-nodes are cloned a lot, so you're doing a lot of allocation. Try using something like [`smallvec`](https://docs.rs/smallvec/1.6.1/smallvec/) or even faster an `[Id; N]` where N is the max number of arguments.

**Comment by bjchambers** [comment]
Good catch. I modified it to use `[Id; 2]` and limit based on the number of children in the operator. Made performance better, but still 5-15% slower than the baseline `math.rs`. Let me know if it would be helpful to send a PR with the test.
Test|Math|Math Struct|Math / Math Struct|1-(Math / Math Struct)                                                            
----|----|-----------|------------------|----------------------
diff_power_harder|21,074,499|23,843,734|88.39%|11.61%
diff_power_simple|5,047,100|5,962,998|84.64%|15.36%
integ_one|1,329,639|1,391,435|95.56%|4.44%
integ_part1|8,189,299|9,364,455|87.45%|12.55%
integ_part2|30,383,957|33,828,950|89.82%|10.18%
integ_part3|3,705,544|4,213,327|87.95%|12.05%
integ_sin|1,340,420|1,399,378|95.79%|4.21%
integ_x|1,401,729|1,475,208|95.02%|4.98%
associate_adds|60,466,286|54,269,233|111.42%|-11.42%
diff_different|1,337,645|1,399,128|95.61%|4.39%
diff_ln|1,350,054|1,408,387|95.86%|4.14%
diff_same|1,321,303|1,361,310|97.06%|2.94%
diff_simple1|3,352,771|3,845,756|87.18%|12.82%
diff_simple2|3,018,403|3,402,892|88.70%|11.30%
powers|1,440,284|1,551,776|92.82%|7.18%
simplify_add|2,648,652|3,003,898|88.17%|11.83%
simplify_const|1,746,411|1,985,554|87.96%|12.04%
simplify_factor|8,295,182|9,450,251|87.78%|12.22%
simplify_root|11,303,834|12,877,045|87.78%|12.22%

**Comment by mwillsey** [comment]
Ok, so 5-15% feels like its ok for this approach. I agree that it's not ideal, but its totally usable.

I think we'll track that work somewhere else, as it's likely to be a pretty large initiative.
