### ISSUE TITLE
Language::display_op should work like other formatting traits

### ISSUE THREAD

**Issue by rosekunkel** [egraphs-good/egg#83]
The rust std library formatting traits (`Display`, `Debug`, `Binary`, etc.) are all structured the same way: they have a single method
```rust
fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result
```
`Language::display_op` should follow the same convention, either by changing its signature:
```rust
fn display_op(&self, f: &mut fmt::Formatter) -> fmt::Result
```
or by separating its functionality out into a new trait:
```rust
pub trait DisplayOp {
    pub fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result;
}
```
Beyond just consistency, this change would also have the added advantage that the operator's string representation could be generated on-the-fly, whereas the current signature (returning `&dyn Display`) requires the implementer to return a reference to some value that already exists. I'm happy to submit a pull request making this change.

**Comment by mwillsey** [comment]
Whoops accidentally closed. This is a great idea. I don’t even remember my reasoning for doing it this way. I would love a PR!

**Comment by mwillsey** [comment]
Actually, could we just have that on the `Language` trait? I don't think there's much utility in making a separate trait.

Now that I think about it, it is a little easier to use this `display_op` method than `fmt`. For example

```rust
format!("My op is {}", enode.display_op())
```

That will become a little more awkward, right?
