### ISSUE TITLE
Source spans & scoping

### ISSUE THREAD

**Issue by MostAwesomeDude** [egraphs-good/egg#85]
Could probably use a better title.

Hi! I have two interrelated concerns from adapting a real-world programming language's backend to use e-graphs. I would like to see explanations for how to handle these problems in the context of `egg`. I read through the `Lambda` test language, and while it was enlightening, it was not a complete explanation.

First, I have source-span information. This is concrete data which is attached to every node in an AST, indicating from which lines in which file the node was originally located. It is a traditional problem in work-sharing optimizers to forget which span is associated with a particular node, and `egg` is no exception. How do y'all normally handle this? Right now, I have a semigroup on source spans, and an e-class analysis which uses that semigroup to conservatively approximate spans. This preserves span information in enough cases.

But second, I have nested scopes with closures, and sometimes variable names are reused. The nature of sharing work in e-graphs naturally causes a confusion over those variables. Is there a simple way to disambiguate the names from closure to closure? Specifically, is there a way to abuse source spans for this? My current thought is that I could do a preliminary name analysis on the entire tree, and rename any shadowed or reused variables. Extremely closely related: Is there a way to achieve automatic alpha-equivalence for lambda-like constructions, or is it always done by encoding alpha-equivalence into the e-match patterns?

I apologize in advance if these aren't actually related questions and they have two distinct answers. They seem like they must interact with each other somehow. I can link [my code](https://github.com/monte-language/typhon/blob/master/mast/lib/mim/meg.mt), but it's not pretty and is still experimental.

Thank you for your hard work and excellent writeups.

**Comment by mwillsey** [comment]
Interesting stuff! A couple points:

- It's not clear than an analysis is the right tool for storing source spans. For example, if you write `10` in many different places, which one is stored in the e-class analysis?
- What are you using source span information for? It seems to me that an e-graph is more useful once you leave the can-still-generate-errors parts of a compiler (parsing, type checking).
- The whole story of binding in an e-graph is somewhat unsatisfactory right now. I think the best technique is _not_ the one in the lambda example: store a representative term for each class in the analysis data, and use _that_ to perform substitution; don't do it in the e-graph itself.
- There is not a known way to get alpha equivalence for free yet. This is an area for future research

**Comment by MostAwesomeDude** [comment]
Thanks for the thoughts. It sounds like, indeed, this is tough.

Right now, when two constants have different spans, we combine them. The actual logic we use right now for combining source spans, [in Python](https://github.com/monte-language/typhon/blob/15c049dd75f17e9de69b26495699de99e3bebf9c/typhon/objects/data.py#L1780-L1818), can handle some situations where an optimized clause might have been smeared out across a single module. But we don't combine spans across modules, which could be a problem. At any rate, this works well enough for prototyping, but it's not a complete solution.

The main use for source spans at runtime is tracebacks. Because we have an `eval()` primitive (this is a flavor of [E](http://www.erights.org/)), these source spans can be un-obvious; think something like "line 1, column 1 of a code literal located at line 5, column 5 of 'test.mt'". We've experimented with compiling this information down to something simpler and more inline, but haven't found a perfect solution yet.

I don't fully understand yet, but it almost seems as if the e-class and its analysis operate as a composite value, rather than as a collection of e-nodes and a summary of the e-nodes. In that case, I might imagine breaking free of the word "approximation" as a description of the summary, since it's more like a maximum or supremum. An e-class with a lambda e-node in its collection will *always* be known as a lambda by its summary.

Sorry that none of this helps. Peace.

**Comment by mwillsey** [comment]
Yes, the analysis value is more like a maximum (it's a least upper bound) of the values of the e-nodes in that e-class.

I think the trouble with spans is do you really want to consider the `11` on line 1 and the `11` on line 500 equivalent? If so, you lose some information. E-class analysis doesn't even come into the picture yet. If you add the `11` on line 1, and then later try to add the second one, you won't actually add anything to the e-graph unless you actually consider the span part of the e-node. If you do, then you have two distinct but equivalent `11`s.

**Comment by MostAwesomeDude** [comment]
Yeah, this is vexing. I guess that I'm just prototyping and experimenting, so maybe some compromises are acceptable. I'll remove source spans entirely from the egg-ish parts of this backend, and see how much further I can get. Thanks for the thoughts, and also for a paper that was detailed enough to allow independent implementations.
