### ISSUE TITLE
Enumerate all equivalent expressions from egraph

### ISSUE THREAD

**Issue by ycunxi** [egraphs-good/egg#87]
Hi,

Is there a tutorial or sample function (or something similar we can look into) about enumerating all equivalent expressions after constructing the egraph ? It looks like each eclass in the egraph corresponds to one RecExpr. Any suggestion will be very helpful.

Thanks!

**Comment by mwillsey** [comment]
There may be infinite terms represented by a single e-graph. If you can be sure to avoid cycles, you could write some kind of recursive, backtracking procedure to do this.

A simple, naive way to do this would pick a 'canonical' e-node for each e-class. If you try every possible way to do this (and throw out all the cycles), that should give you every non-cyclic term.

**Comment by ycunxi** [comment]
Thanks Max. Yes I understand that there could be infinite cases considering cycles. But I think it is possible to enumerate limited number of cases based on cost, e.g., searching for a best cost expression excluding previously found best cost expression(s).

**Comment by mwillsey** [comment]
It is certainly possible. There is not a built in way to do this right now. But I'd love to have it if you could contribute it!
