### ISSUE TITLE
Redesign the Language trait

### ISSUE THREAD

**Issue by rosekunkel** [egraphs-good/egg#89]
Redesign e-nodes, possibly by splitting them up into the operator and the children.

See the discussion in #80.

**Comment by rosekunkel** [comment]
Some design considerations:

## Storing children in unordered collections
We should support use cases like this:
```rust
enum SetLang {
    Union(HashSet<Id>),
    // ...
}
```
Since union is commutative and idempotent, we can treat its arguments as a set instead of a list. This means we don't have to add rewrite rules implementing commutativity and which will blow up the search space. (For commutative non-idempotent operations like `+`, we would need to use a bag/multiset instead.)

## Use a generic argument instead of `Id`
I've run into a few cases where it would have been nice to store other information in an e-node's children. For example, when attempting to unify two e-nodes, it would have been convenient to use `(Id, Id)` as children. (This is not saying `EGraph` should be generic; I expect most of egg would continue to use `Id`'s.)

**Comment by mwillsey** [comment]
Good ideas!

Regarding unordered collections, you could still imagine doing this with slices; just annotate the operator that it's unordered, and then we can sort the children or something to canonicalize them. I think this is better because slices are faster still of a fixed length (egg doesn't really handle variadic operators well yet).

Making e-nodes generic could be interesting. Egg used to do this before it used RecExprs, as this allowed actually recursive expressions.

**Comment by rosekunkel** [comment]
That being said, with macros we could always generate two types:
```rust
enum Calc<T> {
    Num(i32),
    Add(T, T),
}

enum CalcExpr {
    Num(i32),
    Add(Box<CalcExpr>, Box<CalcExpr>),
}
```

**Comment by rosekunkel** [comment]
Also, I don't know if you saw, but I submitted a draft PR for replacing the for_each etc. methods on `Language` with `children()` and `children_mut()` iterators (including updating `define_language!` to generate them): #90

**Comment by mwillsey** [comment]
I already just put the slice requirement back. So maybe we should close this and #90 for now.

You _can_ use some of the HKT emulation tricks to get those sort of recursive types in Rust, but it's really awkward.

**Comment by mwillsey** [comment]
I'm going to close this, feel free to comment and we can reopen if needed.
