### ISSUE TITLE
Web demo seems to be broken

### ISSUE THREAD

**Issue by edko99** [egraphs-good/egg#97]
I entered `(+ 1 2)` then clicked the Run button, but there doesn't seem to be any visible outcome. I tried this in Chrome, Safari, and Firefox. I do see the "running rules" output in the console, but the HTML doesn't seem to update.

**Comment by mwillsey** [comment]
Sorry for the poor interface, I'd really like to improve it (once I get the time!).

You have to hit enter to add the typed-in term to the e-graph. So I believe what's happening in your case is you are running the rules over an empty e-graph.

**Comment by edko99** [comment]
Great! Thank you! I look forward to tinkering with egg!
