### ISSUE TITLE
Possible mistakes in tutorial

### ISSUE THREAD

**Issue by liangyiliang** [egraphs-good/egg#99]
Hi,
In this tutorial page (https://docs.rs/egg/0.6.0/egg/tutorials/_02_getting_started/index.html), we have this example:
![image](https://user-images.githubusercontent.com/16521252/121824375-6721b380-ccde-11eb-8fd4-8e7ee00bd722.png)
It appears that the first assertion will always pass since we did not rebuild the egraph after adding the nodes into the egraph. In particular, I wrote this example which matches for `(TestTestTest ?1 ?1)`. If `egraph.rebuild()` isn't called, nothing will be matched.

```
use egg::{rewrite as rw, *};

define_language! {
    pub enum MyLanguage {
        "TestTestTest" = TestTestTest([Id; 2]),
        Num(i32),
        Symbol(Symbol),
    }
}
fn main() {
    let mut egraph: EGraph<MyLanguage, ()> = Default::default();
    let num1 = egraph.add(MyLanguage::Num(1));
    let ttt = egraph.add(MyLanguage::TestTestTest([num1, num1]));
    egraph.rebuild();            // If this line isn't here, the program will print out 0
    let pat: Pattern<MyLanguage> = "(TestTestTest ?1 ?1)".parse().unwrap();
    let matches = pat.search(&egraph);
    println!("{}", matches.len());
}

```

Does that appear to be correct?

**Comment by mwillsey** [comment]
Great catch! I fixed the example.
